In [1]:
import os
import pandas as pd
import sys
import numpy as np
import time
import schedule
from datetime import datetime

sys.path.insert(0, './_modules')
from db_functions import TheDB
from general_functions import clean_text
#from logging_module import getlogger
#from logging_module_v2 import StartLogger

/home/dev/anaconda3/lib/python3.7/site-packages/tqdm/std.py:648: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel

In [2]:
cwd = os.getcwd()
print(cwd)

/home/dev/sigo_prod_v2

In [3]:
## bots BD connections
conn_dict = {'host':'localhost', 'database': 'brspcqadev',
             'user':'root', 'password':'quito2020'}

cqdb_prod = TheDB(conn_dict)

In [6]:
df = cqdb_prod.GetTable('Screening')

In [8]:
df = df.loc[:, ['mail_id', 'mail_from', 'mail_body']]
df

,mail_id,mail_from,mail_body
0,16e621b40e2a0718,lis-latam@google.com,b'...'
1,16d5f62086593562,lis-latam@google.com,b'...'
2,16c0626420c86643,tatesser@google.com,b'...'
3,16eb93bc25e0f323,lis-latam@google.com,b'...'
4,1700ca8ed5948627,lis-latam@google.com,b'...'
...,...,...,...
42906,1791fbfc16ec319e,lis-latam@google.com,"b'Urgent: 48 hr deadine\r\n\r\nHi team,\r\n\r\..."
42907,1791fc429c9e5d47,lis-latam@google.com,"b'\r\n\r\nHi all,\r\n\r\nAttached the response..."
42908,1791fdb5e93fda1c,lis-latam@google.com,"b'\r\n\r\nHi all,\r\n\r\nAttached the response..."
42909,1791feea83c06f59,lis-latam@google.com,b'\r\n\r\n*FYI - LLC non-BR Target*\r\n\r\nHi ...
42910,179208bc4b000b3a,lis-latam@google.com,"b'\r\n\r\nHi team,\r\n\r\nPlease see below the..."

In [12]:
text = df['mail_body'][42909]
print(text.decode('utf-8'))

*FYI - LLC non-BR Target*

Hi all,

Attached the response letter/planilha for this case. Production was shared
directly with LE via LERS to cloves.nascimento@pc.es.gov.br.

Best,

Ari - LIS

On Tue, Apr 27, 2021 at 15:43 UTC "Artur Rovere" <
artur.rovere@carinaquito.com> wrote:

Hi LIS,



This is related to [4-1970000031618] - c 2021/03/25 - March 25th, 2021 -
CRIMINAL - GMAIL - EXTORTION - TRIX #12951



LE resent the CO with the pages that were missing before. Considering you
already informed us the only target is a FIP account we advise LIS to share
a response letter addressing the issue directly with LE. You may send it
via e-mail to drcc.cartorio@pc.es.gov.br.



Letter should be addressed to: Exmo. Senhor Delegado de Polícia da DRCC em
Vitória/ES - Dr. Brenno Andrade de Souza Silva.



Best,



*De:* lis-latam@google.com <lis-latam@google.com>
*Enviada em:* quinta-feira, 22 de abril de 2021 12:45
*Para:* google@carinaquito.com; alice.matsuo@carinaquito.com;
carina.quito@carinaquito.com; rafael.kohl@carinaquito.com;
vitor.bellotto@carinaquito.com; helena.rossi@carinaquito.com;
mohamad.fares@carinaquito.com; equipe@carinaquito.com;
artur.rovere@carinaquito.com; miriam.singer@carinaquito.com;
bianca.borges@carinaquito.com
*Assunto:* Fwd: [5-7586000031425] Shared LERS Production Available for
Download - Google Reference No. 5506515





Urgent: Espirito Santo / Fines

Hi team,

Please see below the request LIS received. We kindly ask that when you send
this back to us with your interpretation, that you keep the message on this
same thread, so we can easily monitor the case.

We believe this may be related to thread: 4-1970000031618.

Records #[0000693-97 2021.8.08.0050]

Regards, LIS

  ____________

On Thu, Apr 22, 2021 at 14:03 UTC "Delegacia de Repressão aos Crimes
Cibernéticos" <drcc.cartorio@pc.es.gov.br> wrote:

Certifico e dou fé que decisão judicial anteriormente enviada se encontra
legível.



Sirvo-me do presente para REENVIAR decisão judicial, anexo, fl. 24 a 53,
verso, em vista de não localização em portal própria para envio.





Att.

DELEGACIA DE REPRESSÃO AOS CRIMES CIBERNÉTICOS - DRCC
CARTÓRIO - Av. Marechal Campos, 1.236, 2° andar, Bairro Bonfim, Vitória –
ES, CEP: 29047-105
Recepção (27) 3137-2607 — Investigação/fax: (27) 3227-9397 — Cartório: (27)
3137-9106



*De: *"lers" <lers@google.com>
*Para: *"drcc cartorio" <drcc.cartorio@pc.es.gov.br>
*Enviadas: *Sexta-feira, 16 de abril de 2021 17:27:29
*Assunto: *Shared LERS Production Available for Download - Google Reference
No. 5506515



The production for Google Reference Number 5506515, Government Case ID
Proc. 0000693-97.2021.8.08.0050 (IP n.º 004/21 - DRCC 12976), is now
available for download via LERS.

This request was submitted by cloves.nascimento@lers.google. Your email
address was designated by the submitter as requiring access to the
production.

To access the production, please click on the following access link: LERS
<https://lers.google.com/v2/request/4151887?sprt=65c8aec0-10e8-43ea-93b6-75c9ad2a0b37>

You will need to log in with your individual LERS account to access the
download. The link will expire in 14 days.

If the link has expired, please email lis-latam@google.com and include
Google’s reference number to request a new download token.

Regards,
Google Legal Investigations Support

We process your information as described in the Privacy policy
<https://lers.google.com/privacypolicy?hl=pt_BR>.

In [8]:
df_trix = cqdb_prod.GetTable('Trix_Oficial')

In [9]:
df_trix

,line_id,case_id,external_ref_number,deadline,date_received,date_received_cq,auth_last_name,info_case,case_country,email_response,...,date_status_ms,deadline_ms,ms_info,letter_reviewed,user_in_charge_production,production_completed,production_ready,monitor,emissary_chosen,closure
0,1,,0009460-19.2013.403.6181,1946-02-12,1946-02-12,1946-02-12,None,None,None,None,...,1946-02-12,1946-02-12,None,None,0,None,None,0,0,None
1,2,6-9080000028545,0002618-91.2011.403.6181,1946-02-12,1946-02-12,1946-02-12,None,None,None,None,...,1946-02-12,1946-02-12,None,None,0,None,None,0,0,None
2,3,9-5821000001559,0007067-24.2013.403.6181,1946-02-12,1946-02-12,1946-02-12,None,None,None,None,...,1946-02-12,1946-02-12,None,None,0,None,None,0,0,None
3,4,5-6191000002205,,1946-02-12,1946-02-12,1946-02-12,None,None,None,None,...,1946-02-12,1946-02-12,None,None,0,None,None,0,0,None
4,5,9-9709000000828,0076690-72.2011.805.0001,1946-02-12,1946-02-12,1946-02-12,None,None,None,None,...,1946-02-12,1946-02-12,None,None,0,None,None,0,0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10546,10547,missing_value,missing_value,1946-02-12,1946-02-12,1946-02-12,None,None,None,None,...,1946-02-12,1946-02-12,None,None,0,None,None,0,0,None
10547,10548,4-9100000031065,1042340-66.2019.8.13.0024,1946-02-12,1946-02-12,1946-02-12,None,None,None,None,...,1946-02-12,1946-02-12,None,None,0,None,None,0,0,None
10548,10549,3-5849000026727,014055-55.2019.8.06.0001,1946-02-12,1946-02-12,1946-02-12,None,None,None,None,...,1946-02-12,1946-02-12,None,None,0,None,None,0,0,None
10549,10550,missing_value,missing_value,1946-02-12,1946-02-12,1946-02-12,None,None,None,None,...,1946-02-12,1946-02-12,None,None,0,None,None,0,0,None
10550,10551,5-2935000030843,5314-98.2020.811.0015,1946-02-12,1946-02-12,1946-02-12,None,None,None,None,...,1946-02-12,1946-02-12,None,None,0,None,None,0,0,None

In [20]:
cqdb_prod.TablesDataType('Trix')

                                  0            1    2    3     4 5
0                           line_id      int(11)   NO  PRI  None
1                           case_id     longtext  YES       None
2               external_ref_number     longtext  YES       None
3                          deadline  datetime(6)   NO       None
4                     date_received  datetime(6)   NO       None
5                  date_received_cq  datetime(6)   NO       None
6                    auth_last_name     longtext  YES       None
7                         info_case     longtext  YES       None
8                      case_country     longtext  YES       None
9                    email_response     longtext  YES       None
10                           status     longtext  YES       None
11                          targets     longtext  YES       None
12                             lers     longtext  YES       None
13                            label      int(11)   NO          0
14                     date_created  datetime(6)   NO       None
15                    date_modified  datetime(6)   NO       None
16                         users_id      int(11)   NO  MUL     0
17         legal_opinion_background     longtext  YES       None
18         legal_opinion_legal_risk     longtext  YES       None
19    legal_opinion_additional_info     longtext  YES       None
20     legal_opinion_issue_comments     longtext  YES       None
21               legal_opinion_silo     longtext  YES       None
22  legal_opinion_petition_comments     longtext  YES       None
23           user_advice_correction      int(11)   NO          0
24            council_review_letter     longtext  YES       None
25                  writ_filed_date  varchar(45)  YES       None
26                      daily_fines  varchar(45)  YES       None
27             freezing_assets_date  varchar(45)  YES       None
28                  advice_approved      int(11)   NO          0
29            advice_pending_yes_no  varchar(45)  YES       None
30                  advice_pendency  varchar(45)  YES       None
31           advice_pendency_solved  varchar(45)  YES       None
32                      advice_sent      int(11)   NO          0
33                  petition_cat_id      int(11)   NO          0
34          petition_yes_no_pending  varchar(45)  YES       None
35          petition_no_explanation  varchar(45)  YES       None
36                    petition_body  varchar(45)  YES       None
37          petition_draft_prepared  varchar(45)  YES       None
38         petition_draft_corrected  varchar(45)  YES       None
39                   petition_field  varchar(45)  YES       None
40                   ms_draft_write   varchar(3)  YES       None
41                ms_draft_reviewed   varchar(3)  YES       None
42                         ms_filed   varchar(3)  YES       None
43                        status_ms  varchar(45)  YES       None
44                   date_status_ms  datetime(6)   NO       None
45                      deadline_ms  datetime(6)   NO       None
46                          ms_info     longtext  YES       None
47                  letter_reviewed  varchar(45)  YES       None
48        user_in_charge_production      int(11)   NO          0
49             production_completed  varchar(45)  YES       None
50                 production_ready  varchar(45)  YES       None
51                          monitor      int(11)   NO          0
52                  emissary_chosen      int(11)   NO          0
53                          closure  varchar(45)  YES       None

In [17]:
set(df_trix.columns)

{'case_id',
 'date_created',
 'date_modified',
 'date_received',
 'date_received_cq',
 'date_status_ms',
 'deadline',
 'deadline_ms',
 'external_ref_number',
 'line_id',
 'users_id'}

In [5]:
df_screening = cqdb_prod.GetTable('Screening')

In [6]:
print(df_screening.sort_values('date_created', ascending = False).reset_index()['mail_body'][2].decode('utf-8'))

*Last Name*: 7ª Vara Criminal da Comarca de Salvador/BA

*Country: *BR

*External Reference Number*: 0307080-26.2020.8.05.0001

*Date the Court Order was Issued: *2020/10/23

*Date Received: *2020/10/23

*Due Date: *2020/10/30

*Targets*: isaxxx -- Gmail, conxxx -- Gmail

*Info: *n/a

*Trix *#11341

*Related to:* [7-6637000030954]



*LP indicates email for delivery of response:*



Yes (share data directly with LE):

Via LERS



*Counsel needs to review letter: no*



LEGAL OPINION:



1/ Background: this is related to registration data authority request
processed on “RES: [6-2781000030725] 2020/09/11 - Criminal - Authority -
Gmail - Case 2398937 - Outside Counsel - READ”



2/ Legal risks: n/a



3/ Legal issue: NOI is punished with “detenção”. Thus, please solely
provide reg data and logs for the targeted accounts.



4/ Petition: Yes - CQ will file a petition after LIS responds to the CO.



5/ Additional information:

   - LE stipulated DR from 2020/04/18 up until 2020/04/21 on LERS, in
   accordance with the CO.
   - LE called and reiterated the request. He also told us this case is
   related to a State Senator.
   - This is related to registration data authority request. LE got
   judicial authorization and also requested logs, LH and drive data.
   - There is a preservation request for six months.



Letter should be addressed to: Exmo. Senhor Delegado de Polícia da 14ª
Delegacia Territorial de Salvador/BA – Dr. Delmar Araujo Bittencourt.



*Silo*: International Criminal

In [7]:
df_screening

,main_id,mail_id,thread_id,mail_date_received,mail_hms_received,mail_subject,mail_from,mail_body,mail_body_snippet,has_attachment,attachment_folder_link,case_id,external_ref_number,date_created,date_updated,checkd,users_id,id_label
0,1,16e621b40e2a0718,16e3d0dba31c9f02,2019-11-13 00:00:00,2020-04-12 00:13:02,Re: RES: [0-9150000028251] Referente ao Pedido...,lis-latam@google.com,b'...',"Hi all, Attached the response letter for this ...",2,None,0-9150000028251,,2020-08-30 02:28:42,2020-08-30 02:28:42,S,1,1
1,2,16d5f62086593562,16d2ce551f3bb65a,2019-09-23 00:00:00,2020-04-12 18:28:42,Re: [6-5526000027768] - URGENT - 24 HOURS - OV...,lis-latam@google.com,b'...',"Hi all, Attached the response letter for this ...",2,None,6-5526000027768,0000904-07.2019.8.17.0260,2020-08-30 02:28:42,2020-08-30 02:28:42,S,15,1
2,3,16c0626420c86643,16bfb3ebc5852120,2019-07-18 00:00:00,2020-04-12 17:34:13,Re: (TAÍS PLS READ) [1-0673000027027] 2019/07/...,tatesser@google.com,b'...',"Oi Vitor, Como falamos, vamos produzir os dado...",1,None,1-0673000027027,,2020-08-30 02:28:42,2020-08-30 02:28:42,S,1,1
3,4,16eb93bc25e0f323,16eb93bc25e0f323,2019-11-29 00:00:00,2020-04-12 22:15:31,FWD: [5-0366000028367] OFICIO 007900-8/2019,lis-latam@google.com,b'...',"Urgent - Fines Hi team, Please see below the r...",2,None,5-0366000028367,0183.19.007900-8,2020-06-19 21:00:44,2020-06-19 21:00:44,N,0,0
4,5,1700ca8ed5948627,16fe9671f13a5e14,2020-02-03 00:00:00,2020-04-12 20:06:01,Re: [0-5710000029462] - LEGAL ISSUE - c 2020/0...,lis-latam@google.com,b'...',"Hi all, Attached the response letter for this ...",2,None,0-5710000029462,,2020-08-30 02:28:42,2020-08-30 02:28:42,S,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30082,32110,17566fd6b8213ce5,17566fd6b8213ce5,2020-10-26 22:17:26,2020-10-26 22:17:26,[1-2082000030754] - URGENT - 72 HOURS - c 2020...,helena.rossi@carinaquito.com,b'*Last Name*: 4\xc2\xaa Vara Criminal de Arac...,Last Name: 4ª Vara Criminal de Aracaju/SE Coun...,2,/home/dev/sigo_prod/_attachments/17566fd6b8213ce5,1-2082000030754,0018229-37.2020.8.25.0001,2020-10-26 22:27:41,2020-10-26 22:27:41,N,0,0
30083,32111,175670b082979f82,175670b082979f82,2020-10-26 22:32:57,2020-10-26 22:32:57,FWD: [9-8283000030756] BR Data Request 3100067...,lis-latam@google.com,b'\r\n\r\nUrgent: 5 days deadline.\r\n\r\nReco...,Urgent: 5 days deadline. Records #[5008453-83....,2,/home/dev/sigo_prod/_attachments/175670b082979f82,9-8283000030756,5008453-83.2020.8.24.0023,2020-10-26 22:38:05,2020-10-26 22:38:05,N,0,0
30084,32112,17567099bfd9ea26,17567099bfd9ea26,2020-10-26 22:31:20,2020-10-26 22:31:20,[7-6637000030954] - LEGAL ISSUE - c 2020/10/30...,helena.rossi@carinaquito.com,b'*Last Name*: 7\xc2\xaa Vara Criminal da Coma...,Last Name: 7ª Vara Criminal da Comarca de Salv...,2,/home/dev/sigo_prod/_attachments/17567099bfd9ea26,7-6637000030954,0307080-26.2020.8.05.0001,2020-10-26 22:38:05,2020-10-26 22:38:05,N,0,0
30085,32113,1756706f2419d084,17546928d9c3172b,2020-10-26 22:28:29,2020-10-26 22:28:29,Re: RES: [8-0414000030853] - c 2020/10/23 - Oc...,lis-latam@google.com,"b'\r\n\r\nHi all,\r\n\r\nAttached the response...","Hi all, Attached the response letter/planilha ...",2,/home/dev/sigo_prod/_attachments/1756706f2419d084,8-0414000030853,5003850-43.2020.8.24.0030,2020-10-26 22:38:05,2020-10-26 22:38:05,N,0,0
30086,32114,1756706e769d9ae3,1756706e769d9ae3,2020-10-26 22:28:23,2020-10-26 22:28:23,"FWD: [4-5372000030654] BR Data Request, Ext Re...",lis-latam@google.com,b'\r\n\r\nUrgent: Child Exploitation\r\n\r\nRe...,Urgent: Child Exploitation Records # [73/2020/...,2,/home/dev/sigo_prod/_attachments/1756706e769d9ae3,4-5372000030654,,2020-10-26 22:38:05,2020-10-26 22:38:05,N,0,0

In [11]:
cqdb_prod.TablesList()

['Access_level',
 'Address',
 'Bancos',
 'Delivery_Check',
 'Emissary',
 'Emissary_Status',
 'IP_block',
 'Label',
 'Monitoring',
 'Rating',
 'Role',
 'Screening',
 'Trix',
 'Users',
 'Users_status']

In [32]:
cqdb.TablesDataType('screening_table')

,0,1,2,3,4,5
0,main_id,int(11),NO,PRI,None,auto_increment
1,mail_id,varchar(50),NO,,None,
2,thread_id,varchar(50),NO,,None,
3,mail_date_received,date,NO,,None,
4,mail_hms_received,time,NO,,None,
5,mail_subject,varchar(10000),NO,,None,
6,mail_from,varchar(60),NO,,None,
7,mail_body,longblob,YES,,None,
8,mail_body_snippet,varchar(5000),YES,,None,
9,has_attachment,"enum('0','1')",NO,,None,
10,attachment_folder_link,varchar(50),YES,,None,
11,case_id,varchar(50),YES,,None,
12,external_ref_number,varchar(50),YES,,None,
13,date_created,timestamp,NO,,CURRENT_TIMESTAMP,on update CURRENT_TIMESTAMP
14,date_updated,timestamp,NO,,CURRENT_TIMESTAMP,on update CURRENT_TIMESTAMP

In [45]:
cqdb_prod.TablesDataType('Screening')

,0,1,2,3,4,5
0,main_id,int(11),NO,PRI,None,auto_increment
1,mail_id,varchar(50),NO,,None,
2,thread_id,varchar(50),NO,,None,
3,mail_date_received,datetime,NO,,None,
4,mail_hms_received,datetime,NO,,None,
5,mail_subject,varchar(10000),NO,,None,
6,mail_from,varchar(60),NO,,None,
7,mail_body,longblob,YES,,None,
8,mail_body_snippet,varchar(5000),YES,,None,
9,has_attachment,int(11),NO,,None,
10,attachment_folder_link,varchar(50),YES,,None,
11,case_id,varchar(50),YES,,None,
12,external_ref_number,varchar(50),YES,,None,
13,date_created,datetime,NO,,CURRENT_TIMESTAMP,on update CURRENT_TIMESTAMP
14,date_updated,datetime,NO,,CURRENT_TIMESTAMP,on update CURRENT_TIMESTAMP
15,checkd,varchar(1),YES,,N,

In [34]:
df_test = pd.DataFrame(columns = ['mail_id', 'thread_id', 'mail_date_received',\
                                  'mail_hms_received', 'mail_subject', 'mail_from', 'mail_body',\
                                  'mail_body_snippet', 'has_attachment', 'attachment_folder_link', 
                                  'case_id', 'external_ref_number'])

datetime.datetime(2020, 7, 1, 1, 36, 17, 473834)

In [189]:
df_test.at[0, 'mail_id'] = 'bláblá'
df_test.at[0, 'thread_id'] = 'teste'
df_test.at[0, 'mail_date_received'] = datetime.today()
df_test.at[0, 'mail_hms_received'] = datetime.today()
df_test.at[0, 'mail_subject'] = 'teste'
df_test.at[0, 'mail_from'] = 'teste'
df_test.at[0, 'mail_body'] = 'teste'
df_test.at[0, 'mail_body_snippet'] = 'teste'
df_test.at[0, 'has_attachment'] = 0
df_test.at[0, 'attachment_folder_link'] = 'teste'
df_test.at[0, 'case_id'] = 'teste'
df_test.at[0, 'external_ref_number'] = 'teste'

In [190]:
df_test

,mail_id,thread_id,mail_date_received,mail_hms_received,mail_subject,mail_from,mail_body,mail_body_snippet,has_attachment,attachment_folder_link,case_id,external_ref_number
0,bláblá,teste,2020-07-01 03:12:43.342260,2020-07-01 03:12:43.342331,teste,teste,teste,teste,0,teste,teste,teste

In [191]:
from sqlalchemy import create_engine
## create sqlalchemy engine
engine = create_engine("mysql://{user}:{pw}@localhost/{db}?charset=utf8mb4"
                       .format(user="root",
                               pw="quito2020",
                               db='brspcqadev'), encoding="utf8")
#logging.info('Loading MySQL database.')

## Insert whole DataFrame into MySQL
df_test.to_sql('Screening', con = engine, if_exists = 'append', index = False, chunksize = 1000)
#logging.info('Data written to MySQL database.')
engine.dispose()

In [167]:
data_path = os.path.join(cwd, '_collect_control')

In [168]:
interest_list = [item for item in os.listdir(data_path) if '.csv' in item]
interest_list

['to_data.csv', 'att_data.csv', 'log.csv', 'mid_base.csv']

In [180]:
df = pd.read_csv(os.path.join(data_path, 'att_data.csv'), sep = '\t', encoding = 'utf-8')

In [181]:
df

,mail_id,doc_name,doc_link
0,16e7f52e8897940d,316:2019.pdf,/home/dev/sigo/_attachments/16e7f52e8897940d/3...
1,16efbfe76f3c98a7,02367-2019_Redacted.pdf,/home/dev/sigo/_attachments/16efbfe76f3c98a7/0...
2,16c73a4539a90832,Court Order #6429.pdf,/home/dev/sigo/_attachments/16c73a4539a90832/C...
3,16ea8eba4927ca92,592-2019_Redacted.pdf,/home/dev/sigo/_attachments/16ea8eba4927ca92/5...
4,16fe846f16206c67,01 2020_Redacted.pdf,/home/dev/sigo/_attachments/16fe846f16206c67/0...
...,...,...,...
26188,172c5341982c58f3,0041479-74.2019.8.19.0204.pdf,/home/dev/sigo/_attachments/172c5341982c58f3/0...
26189,172c566d6dbdf62a,0084905-32.2020.8.19.0001.pdf,/home/dev/sigo/_attachments/172c566d6dbdf62a/0...
26190,172c57bd972c08e2,Carta IMEI 3775615.pdf,/home/dev/sigo/_attachments/172c57bd972c08e2/C...
26191,172c58f3a4e63932,Carta IMEI 3782932.pdf,/home/dev/sigo/_attachments/172c58f3a4e63932/C...
26192,172c596e40652f46,77-2020.pdf,/home/dev/sigo/_attachments/172c596e40652f46/7...

In [182]:
df_screening = cqdb_prod.GetTable('Screening', 'main_id, mail_id')
df_att_final = df_screening.merge(df, on = 'mail_id', how = 'right').dropna()
df_att_final['main_id'] = df_att_final['main_id'].astype(int)
df_att_final = df_att_final.drop('mail_id', axis = 1)
df_att_final

,main_id,doc_name,doc_link
0,1,3085942 (2).pdf,/home/dev/sigo/_attachments/16e621b40e2a0718/3...
1,2,2750653.pdf,/home/dev/sigo/_attachments/16d5f62086593562/2...
2,4,007900-8-2019_Redacted.pdf,/home/dev/sigo/_attachments/16eb93bc25e0f323/0...
3,5,3431332.pdf,/home/dev/sigo/_attachments/1700ca8ed5948627/3...
4,7,2741646.pdf,/home/dev/sigo/_attachments/16d458e153577d22/2...
...,...,...,...
1505,999,0056550-98.2019.8.26.0050_Redacted.pdf,/home/dev/sigo/_attachments/16ef0c6ba7626c7f/0...
1506,1000,Court Order #7145.pdf,/home/dev/sigo/_attachments/16dd6c87c63b0154/C...
1507,1000,Court Order #7145.pdf,/home/dev/sigo/_attachments/16dd6c87c63b0154/C...
1508,1002,316:2019.pdf,/home/dev/sigo/_attachments/16e7f52e8897940d/3...
1509,1002,316:2019.pdf,/home/dev/sigo/_attachments/16e7f52e8897940d/3...

In [186]:
cqdb_prod.TablesDataType('Attachment')

,0,1,2,3,4,5
0,attachment_id,int(11),NO,PRI,None,auto_increment
1,main_id,int(11),NO,MUL,None,
2,doc_name,varchar(500),YES,,None,
3,doc_link,varchar(500),YES,,None,
4,date_created,timestamp,NO,,CURRENT_TIMESTAMP,on update CURRENT_TIMESTAMP
5,date_updated,timestamp,NO,,CURRENT_TIMESTAMP,on update CURRENT_TIMESTAMP

In [187]:
#df_att_final['doc_link'] = df_att_final['doc_link'].str.encode('utf-8') 
#df_att_final['doc_name'] = df_att_final['doc_name'].str.encode('utf-8').astype(str)

In [188]:
for k in range(0, len(df_att_final)):
    df_row = df_att_final.loc[k, :].to_frame().T
    result = cqdb_prod.InsertDB(df_row, 'Attachment', key_column = 'doc_link', return_table = False)
    print(k)
    print(' ')
    print(' ')

Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
0


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
1


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
2


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
3


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
4


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
5


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
6


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
7


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
8


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
9


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
10


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
11


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
12


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
13


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
14


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
15


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
16


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
17


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
18


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
19


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
20


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
21


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
22


Original length: 1
DB length: 1876
Final length: 0
No data to be written in the db.
23


Original length: 1
DB length: 1876
Final length: 1
Success! Data writtten in db!
24


Original length: 1
DB length: 1877
Final length: 0
No data to be written in the db.
25


Original length: 1
DB length: 1877
Final length: 1
Success! Data writtten in db!
26


Original length: 1
DB length: 1878
Final length: 0
No data to be written in the db.
27


Original length: 1
DB length: 1878
Final length: 0
No data to be written in the db.
28


Original length: 1
DB length: 1878
Final length: 0
No data to be written in the db.
29


Original length: 1
DB length: 1878
Final length: 0
No data to be written in the db.
30


Original length: 1
DB length: 1878
Final length: 0
No data to be written in the db.
31


Original length: 1
DB length: 1878
Final length: 0
No data to be written in the db.
32


Original length: 1
DB length: 1878
Final length: 0
No data to be written in the db.
33


Original length: 1
DB length: 1878
Final length: 0
No data to be written in the db.
34


Original length: 1
DB length: 1878
Final length: 0
No data to be written in the db.
35


Original length: 1
DB length: 1878
Final length: 0
No data to be written in the db.
36


Original length: 1
DB length: 1878
Final length: 0
No data to be written in the db.
37


Original length: 1
DB length: 1878
Final length: 0
No data to be written in the db.
38


Original length: 1
DB length: 1878
Final length: 1
Success! Data writtten in db!
39


Original length: 1
DB length: 1879
Final length: 0
No data to be written in the db.
40


Original length: 1
DB length: 1879
Final length: 0
No data to be written in the db.
41


Original length: 1
DB length: 1879
Final length: 0
No data to be written in the db.
42


Original length: 1
DB length: 1879
Final length: 0
No data to be written in the db.
43


Original length: 1
DB length: 1879
Final length: 0
No data to be written in the db.
44


Original length: 1
DB length: 1879
Final length: 0
No data to be written in the db.
45


Original length: 1
DB length: 1879
Final length: 0
No data to be written in the db.
46


Original length: 1
DB length: 1879
Final length: 1
Success! Data writtten in db!
47


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
48


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
49


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
50


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
51


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
52


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
53


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
54


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
55


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
56


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
57


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
58


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
59


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
60


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
61


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
62


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
63


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
64


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
65


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
66


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
67


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
68


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
69


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
70


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
71


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
72


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
73


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
74


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
75


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
76


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
77


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
78


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
79


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
80


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
81


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
82


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
83


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
84


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
85


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
86


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
87


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
88


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
89


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
90


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
91


Original length: 1

DB length: 1880
Final length: 0
No data to be written in the db.
92


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
93


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
94


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
95


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
96


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
97


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
98


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
99


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
100


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
101


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
102


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
103


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
104


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
105


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
106


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
107


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
108


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
109


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
110


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
111


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
112


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
113


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
114


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
115


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
116


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
117


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
118


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
119


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
120


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
121


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
122


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
123


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
124


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
125


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
126


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
127


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
128


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
129


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
130


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
131


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
132


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
133


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
134


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
135


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
136


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
137


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
138


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
139


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
140


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
141


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
142


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
143


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
144


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
145


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
146


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
147


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
148


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
149


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
150


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
151


Original length: 1
DB length: 1880
Final length: 0
No data to be written in the db.
152


Original length: 1
DB length: 1880
Final length: 1
Success! Data writtten in db!
153


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
154


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
155


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
156


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
157


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
158


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
159


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
160


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
161


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
162


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
163


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
164


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
165


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
166


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
167


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
168


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
169


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
170


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
171


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
172


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
173


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
174


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
175


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
176


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
177


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
178


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
179


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
180


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
181


Original length: 1

DB length: 1881
Final length: 0
No data to be written in the db.
182


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
183


Original length: 1
DB length: 1881
Final length: 0
No data to be written in the db.
184


Original length: 1
DB length: 1881
Final length: 1
Success! Data writtten in db!
185


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
186


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
187


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
188


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
189


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
190


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
191


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
192


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
193


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
194


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
195


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
196


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
197


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
198


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
199


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
200


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
201


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
202


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
203


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
204


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
205


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
206


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
207


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
208


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
209


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
210


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
211


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
212


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
213


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
214


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
215


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
216


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
217


Original length: 1
DB length: 1882
Final length: 0
No data to be written in the db.
218


Original length: 1
DB length: 1882
Final length: 1
Success! Data writtten in db!
219


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
220


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
221


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
222


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
223


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
224


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
225


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
226


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
227


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
228


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
229


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
230


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
231


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
232


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
233


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
234


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
235


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
236


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
237


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
238


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
239


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
240


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
241


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
242


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
243


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
244


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
245


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
246


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
247


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
248


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
249


Original length: 1
DB length: 1883
Final length: 0
No data to be written in the db.
250


Original length: 1
DB length: 1883
Final length: 1
Success! Data writtten in db!
251


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
252


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
253


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
254


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
255


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
256


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
257


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
258


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
259


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
260


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
261


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
262


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
263


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
264


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
265


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
266


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
267


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
268


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
269


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
270


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
271


Original length: 1

DB length: 1884
Final length: 0
No data to be written in the db.
272


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
273


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
274


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
275


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
276


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
277


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
278


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
279


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
280


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
281


Original length: 1
DB length: 1884
Final length: 0
No data to be written in the db.
282


Original length: 1
DB length: 1884
Final length: 1
Success! Data writtten in db!
283


Original length: 1
DB length: 1885
Final length: 1
Success! Data writtten in db!
284


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
285


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
286


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
287


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
288


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
289


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
290


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
291


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
292


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
293


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
294


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
295


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
296


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
297


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
298


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
299


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
300


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
301


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
302


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
303


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
304


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
305


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
306


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
307


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
308


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
309


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
310


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
311


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
312


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
313


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
314


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
315


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
316


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
317


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
318


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
319


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
320


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
321


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
322


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
323


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
324


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
325


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
326


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
327


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
328


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
329


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
330


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
331


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
332


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
333


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
334


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
335


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
336


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
337


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
338


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
339


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
340


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
341


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
342


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
343


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
344


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
345


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
346


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
347


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
348


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
349


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
350


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
351


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
352


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
353


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
354


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
355


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
356


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
357


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
358


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
359


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
360


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
361


Original length: 1

DB length: 1886
Final length: 0
No data to be written in the db.
362


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
363


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
364


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
365


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
366


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
367


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
368


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
369


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
370


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
371


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
372


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
373


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
374


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
375


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
376


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
377


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
378


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
379


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
380


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
381


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
382


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
383


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
384


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
385


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
386


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
387


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
388


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
389


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
390


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
391


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
392


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
393


Original length: 1
DB length: 1886
Final length: 0
No data to be written in the db.
394


Original length: 1
DB length: 1886
Final length: 1
Success! Data writtten in db!
395


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
396


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
397


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
398


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
399


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
400


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
401


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
402


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
403


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
404


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
405


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
406


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
407


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
408


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
409


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
410


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
411


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
412


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
413


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
414


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
415


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
416


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
417


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
418


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
419


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
420


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
421


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
422


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
423


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
424


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
425


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
426


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
427


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
428


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
429


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
430


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
431


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
432


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
433


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
434


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
435


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
436


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
437


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
438


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
439


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
440


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
441


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
442


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
443


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
444


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
445


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
446


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
447


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
448


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
449


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
450


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
451


Original length: 1

DB length: 1887
Final length: 0
No data to be written in the db.
452


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
453


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
454


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
455


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
456


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
457


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
458


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
459


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
460


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
461


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
462


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
463


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
464


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
465


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
466


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
467


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
468


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
469


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
470


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
471


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
472


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
473


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
474


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
475


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
476


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
477


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
478


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
479


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
480


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
481


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
482


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
483


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
484


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
485


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
486


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
487


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
488


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
489


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
490


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
491


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
492


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
493


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
494


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
495


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
496


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
497


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
498


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
499


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
500


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
501


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
502


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
503


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
504


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
505


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
506


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
507


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
508


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
509


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
510


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
511


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
512


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
513


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
514


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
515


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
516


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
517


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
518


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
519


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
520


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
521


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
522


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
523


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
524


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
525


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
526


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
527


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
528


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
529


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
530


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
531


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
532


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
533


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
534


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
535


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
536


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
537


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
538


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
539


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
540


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
541


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
542


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
543


Original length: 1

DB length: 1887
Final length: 0
No data to be written in the db.
544


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
545


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
546


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
547


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
548


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
549


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
550


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
551


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
552


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
553


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
554


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
555


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
556


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
557


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
558


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
559


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
560


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
561


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
562


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
563


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
564


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
565


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
566


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
567


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
568


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
569


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
570


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
571


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
572


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
573


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
574


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
575


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
576


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
577


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
578


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
579


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
580


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
581


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
582


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
583


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
584


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
585


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
586


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
587


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
588


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
589


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
590


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
591


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
592


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
593


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
594


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
595


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
596


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
597


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
598


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
599


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
600


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
601


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
602


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
603


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
604


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
605


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
606


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
607


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
608


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
609


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
610


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
611


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
612


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
613


Original length: 1
DB length: 1887
Final length: 0
No data to be written in the db.
614


Original length: 1
DB length: 1887
Final length: 1
Success! Data writtten in db!
615


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
616


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
617


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
618


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
619


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
620


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
621


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
622


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
623


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
624


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
625


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
626


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
627


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
628


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
629


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
630


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
631


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
632


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
633


Original length: 1

DB length: 1888
Final length: 0
No data to be written in the db.
634


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
635


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
636


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
637


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
638


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
639


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
640


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
641


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
642


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
643


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
644


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
645


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
646


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
647


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
648


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
649


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
650


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
651


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
652


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
653


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
654


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
655


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
656


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
657


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
658


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
659


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
660


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
661


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
662


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
663


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
664


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
665


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
666


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
667


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
668


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
669


Original length: 1
DB length: 1888
Final length: 0
No data to be written in the db.
670


Original length: 1
DB length: 1888
Final length: 1
Success! Data writtten in db!
671


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
672


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
673


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
674


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
675


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
676


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
677


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
678


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
679


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
680


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
681


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
682


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
683


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
684


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
685


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
686


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
687


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
688


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
689


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
690


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
691


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
692


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
693


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
694


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
695


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
696


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
697


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
698


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
699


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
700


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
701


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
702


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
703


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
704


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
705


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
706


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
707


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
708


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
709


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
710


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
711


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
712


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
713


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
714


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
715


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
716


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
717


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
718


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
719


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
720


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
721


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
722


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
723


Original length: 1

DB length: 1889
Final length: 0
No data to be written in the db.
724


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
725


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
726


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
727


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
728


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
729


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
730


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
731


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
732


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
733


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
734


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
735


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
736


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
737


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
738


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
739


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
740


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
741


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
742


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
743


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
744


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
745


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
746


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
747


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
748


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
749


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
750


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
751


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
752


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
753


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
754


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
755


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
756


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
757


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
758


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
759


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
760


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
761


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
762


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
763


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
764


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
765


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
766


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
767


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
768


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
769


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
770


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
771


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
772


Original length: 1
DB length: 1889
Final length: 0
No data to be written in the db.
773


Original length: 1
DB length: 1889
Final length: 1
Success! Data writtten in db!
774


Original length: 1
DB length: 1890
Final length: 0
No data to be written in the db.
775


Original length: 1
DB length: 1890
Final length: 1
Success! Data writtten in db!
776


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
777


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
778


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
779


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
780


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
781


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
782


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
783


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
784


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
785


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
786


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
787


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
788


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
789


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
790


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
791


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
792


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
793


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
794


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
795


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
796


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
797


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
798


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
799


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
800


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
801


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
802


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
803


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
804


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
805


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
806


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
807


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
808


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
809


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
810


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
811


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
812


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
813


Original length: 1

DB length: 1891
Final length: 0
No data to be written in the db.
814


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
815


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
816


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
817


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
818


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
819


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
820


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
821


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
822


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
823


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
824


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
825


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
826


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
827


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
828


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
829


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
830


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
831


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
832


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
833


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
834


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
835


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
836


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
837


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
838


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
839


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
840


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
841


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
842


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
843


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
844


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
845


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
846


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
847


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
848


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
849


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
850


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
851


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
852


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
853


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
854


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
855


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
856


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
857


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
858


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
859


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
860


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
861


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
862


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
863


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
864


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
865


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
866


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
867


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
868


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
869


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
870


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
871


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
872


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
873


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
874


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
875


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
876


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
877


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
878


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
879


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
880


Original length: 1
DB length: 1891
Final length: 0
No data to be written in the db.
881


Original length: 1
DB length: 1891
Final length: 1
Success! Data writtten in db!
882


Original length: 1
DB length: 1892
Final length: 0
No data to be written in the db.
883


Original length: 1
DB length: 1892
Final length: 0
No data to be written in the db.
884


Original length: 1
DB length: 1892
Final length: 0
No data to be written in the db.
885


Original length: 1
DB length: 1892
Final length: 0
No data to be written in the db.
886


Original length: 1
DB length: 1892
Final length: 0
No data to be written in the db.
887


Original length: 1
DB length: 1892
Final length: 0
No data to be written in the db.
888


Original length: 1
DB length: 1892
Final length: 0
No data to be written in the db.
889


Original length: 1
DB length: 1892
Final length: 1
Success! Data writtten in db!
890


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
891


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
892


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
893


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
894


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
895


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
896


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
897


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
898


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
899


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
900


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
901


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
902


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
903


Original length: 1

DB length: 1893
Final length: 0
No data to be written in the db.
904


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
905


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
906


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
907


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
908


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
909


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
910


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
911


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
912


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
913


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
914


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
915


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
916


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
917


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
918


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
919


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
920


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
921


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
922


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
923


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
924


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
925


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
926


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
927


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
928


Original length: 1
DB length: 1893
Final length: 0
No data to be written in the db.
929


Original length: 1
DB length: 1893
Final length: 1
Success! Data writtten in db!
930


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
931


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
932


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
933


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
934


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
935


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
936


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
937


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
938


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
939


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
940


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
941


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
942


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
943


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
944


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
945


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
946


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
947


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
948


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
949


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
950


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
951


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
952


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
953


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
954


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
955


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
956


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
957


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
958


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
959


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
960


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
961


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
962


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
963


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
964


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
965


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
966


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
967


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
968


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
969


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
970


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
971


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
972


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
973


Original length: 1
DB length: 1894
Final length: 0
No data to be written in the db.
974


Original length: 1
DB length: 1894
Final length: 1
Success! Data writtten in db!
975


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
976


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
977


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
978


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
979


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
980


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
981


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
982


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
983


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
984


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
985


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
986


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
987


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
988


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
989


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
990


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
991


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
992


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
993


Original length: 1

DB length: 1895
Final length: 0
No data to be written in the db.
994


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
995


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
996


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
997


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
998


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
999


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1000


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1001


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1002


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1003


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1004


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1005


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1006


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1007


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1008


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1009


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1010


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1011


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1012


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1013


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1014


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1015


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1016


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1017


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1018


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1019


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1020


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1021


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1022


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1023


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1024


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1025


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1026


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1027


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1028


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1029


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1030


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1031


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1032


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1033


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1034


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1035


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1036


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1037


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1038


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1039


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1040


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1041


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1042


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1043


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1044


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1045


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1046


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1047


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1048


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1049


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1050


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1051


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1052


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1053


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1054


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1055


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1056


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1057


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1058


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1059


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1060


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1061


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1062


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1063


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1064


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1065


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1066


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1067


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1068


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1069


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1070


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1071


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1072


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1073


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1074


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1075


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1076


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1077


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1078


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1079


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1080


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1081


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1082


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1083


Original length: 1

DB length: 1895
Final length: 0
No data to be written in the db.
1084


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1085


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1086


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1087


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1088


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1089


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1090


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1091


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1092


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1093


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1094


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1095


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1096


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1097


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1098


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1099


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1100


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1101


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1102


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1103


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1104


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1105


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1106


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1107


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1108


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1109


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1110


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1111


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1112


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1113


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1114


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1115


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1116


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1117


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1118


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1119


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1120


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1121


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1122


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1123


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1124


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1125


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1126


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1127


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1128


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1129


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1130


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1131


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1132


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1133


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1134


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1135


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1136


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1137


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1138


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1139


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1140


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1141


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1142


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1143


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1144


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1145


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1146


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1147


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1148


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1149


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1150


Original length: 1
DB length: 1895
Final length: 0
No data to be written in the db.
1151


Original length: 1
DB length: 1895
Final length: 1
Success! Data writtten in db!
1152


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1153


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1154


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1155


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1156


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1157


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1158


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1159


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1160


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1161


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1162


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1163


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1164


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1165


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1166


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1167


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1168


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1169


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1170


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1171


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1172


Original length: 1

DB length: 1896
Final length: 0
No data to be written in the db.
1173


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1174


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1175


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1176


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1177


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1178


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1179


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1180


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1181


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1182


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1183


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1184


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1185


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1186


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1187


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1188


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1189


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1190


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1191


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1192


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1193


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1194


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1195


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1196


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1197


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1198


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1199


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1200


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1201


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1202


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1203


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1204


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1205


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1206


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1207


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1208


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1209


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1210


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1211


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1212


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1213


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1214


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1215


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1216


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1217


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1218


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1219


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1220


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1221


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1222


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1223


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1224


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1225


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1226


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1227


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1228


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1229


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1230


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1231


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1232


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1233


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1234


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1235


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1236


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1237


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1238


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1239


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1240


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1241


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1242


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1243


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1244


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1245


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1246


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1247


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1248


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1249


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1250


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1251


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1252


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1253


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1254


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1255


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1256


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1257


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1258


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1259


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1260


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1261


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1262


Original length: 1

DB length: 1896
Final length: 0
No data to be written in the db.
1263


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1264


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1265


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1266


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1267


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1268


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1269


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1270


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1271


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1272


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1273


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1274


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1275


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1276


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1277


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1278


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1279


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1280


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1281


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1282


Original length: 1
DB length: 1896
Final length: 0
No data to be written in the db.
1283


Original length: 1
DB length: 1896
Final length: 1
Success! Data writtten in db!
1284


Original length: 1
DB length: 1897
Final length: 0
No data to be written in the db.
1285


Original length: 1
DB length: 1897
Final length: 1
Success! Data writtten in db!
1286


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1287


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1288


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1289


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1290


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1291


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1292


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1293


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1294


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1295


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1296


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1297


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1298


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1299


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1300


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1301


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1302


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1303


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1304


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1305


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1306


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1307


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1308


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1309


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1310


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1311


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1312


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1313


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1314


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1315


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1316


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1317


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1318


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1319


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1320


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1321


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1322


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1323


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1324


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1325


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1326


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1327


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1328


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1329


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1330


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1331


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1332


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1333


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1334


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1335


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1336


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1337


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1338


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1339


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1340


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1341


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1342


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1343


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1344


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1345


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1346


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1347


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1348


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1349


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1350


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1351


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1352


Original length: 1

DB length: 1898
Final length: 0
No data to be written in the db.
1353


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1354


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1355


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1356


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1357


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1358


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1359


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1360


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1361


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1362


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1363


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1364


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1365


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1366


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1367


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1368


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1369


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1370


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1371


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1372


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1373


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1374


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1375


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1376


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1377


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1378


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1379


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1380


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1381


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1382


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1383


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1384


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1385


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1386


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1387


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1388


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1389


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1390


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1391


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1392


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1393


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1394


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1395


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1396


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1397


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1398


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1399


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1400


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1401


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1402


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1403


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1404


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1405


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1406


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1407


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1408


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1409


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1410


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1411


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1412


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1413


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1414


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1415


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1416


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1417


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1418


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1419


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1420


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1421


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1422


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1423


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1424


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1425


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1426


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1427


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1428


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1429


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1430


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1431


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1432


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1433


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1434


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1435


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1436


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1437


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1438


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1439


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1440


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1441


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1442


Original length: 1

DB length: 1898
Final length: 0
No data to be written in the db.
1443


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1444


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1445


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1446


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1447


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1448


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1449


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1450


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1451


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1452


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1453


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1454


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1455


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1456


Original length: 1
DB length: 1898
Final length: 0
No data to be written in the db.
1457


Original length: 1
DB length: 1898
Final length: 1
Success! Data writtten in db!
1458


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1459


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1460


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1461


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1462


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1463


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1464


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1465


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1466


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1467


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1468


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1469


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1470


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1471


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1472


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1473


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1474


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1475


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1476


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1477


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1478


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1479


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1480


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1481


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1482


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1483


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1484


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1485


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1486


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1487


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1488


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1489


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1490


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1491


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1492


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1493


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1494


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1495


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1496


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1497


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1498


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1499


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1500


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1501


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1502


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1503


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1504


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1505


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1506


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1507


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1508


Original length: 1
DB length: 1899
Final length: 0
No data to be written in the db.
1509

In [243]:
cqdb_prod.GetTable('Attachment')

,attachment_id,main_id,doc_name,doc_link,date_created,date_updated
0,1,313,Court Order #6121 (2).pdf,/home/dev/sigo/_attachments/16c4a30fa32a3372/C...,2020-07-01 02:36:37,2020-07-01 02:36:37
1,2,783,2739214.pdf,/home/dev/sigo/_attachments/16d17110dfc5c084/2...,2020-07-01 02:37:45,2020-07-01 02:37:45
2,3,313,Court Order #6121 (2).pdf,/home/dev/sigo/_attachments/16c4a30fa32a3372/C...,2020-07-01 02:37:45,2020-07-01 02:37:45
3,4,513,Court Order #7590.pdf,/home/dev/sigo/_attachments/16edd8063bb86128/C...,2020-07-01 02:37:53,2020-07-01 02:37:53
4,5,313,Court Order #6121 (2).pdf,/home/dev/sigo/_attachments/16c4a30fa32a3372/C...,2020-07-01 02:37:53,2020-07-01 02:37:53
...,...,...,...,...,...,...
12661,13284,14351,0000082-14.2019.4.01.3100_Redacted.pdf,/home/dev/sigo_prod/_attachments/16eccb4b4d827...,2020-07-01 21:11:37,2020-07-01 21:11:37
12662,13285,14352,703_Redacted.pdf,/home/dev/sigo_prod/_attachments/17179aa54dfe9...,2020-07-01 21:11:37,2020-07-01 21:11:37
12663,13286,14352,712_Redacted.pdf,/home/dev/sigo_prod/_attachments/17179aa54dfe9...,2020-07-01 21:11:37,2020-07-01 21:11:37
12664,13287,14353,Ref+3729968.pdf,/home/dev/sigo_prod/_attachments/172387825e9ad...,2020-07-01 21:11:37,2020-07-01 21:11:37
12665,13288,14354,Court Order #8804.pdf,/home/dev/sigo_prod/_attachments/171bcfa58a6c8...,2020-07-01 21:11:37,2020-07-01 21:11:37

In [247]:
df_screening = cqdb_prod.GetTable('Screening')
df_screening.sort_values('mail_date_received', ascending = False)

,main_id,mail_id,thread_id,mail_date_received,mail_hms_received,mail_subject,mail_from,mail_body,mail_body_snippet,has_attachment,attachment_folder_link,case_id,external_ref_number,date_created,date_updated,checkd
15240,15482,1730c50c98e05d33,172e84f1fc58e356,2020-07-01 21:38:07,2020-07-01 21:38:07,Re: [4-7094000030822] BR Data Request 0003789-...,lis-latam@google.com,"b'\r\n\r\nHi all,\r\n\r\nAttached the response...","Hi all, Attached the response letter/planilha ...",2,/home/dev/sigo_prod/_attachments/1730c50c98e05d33,4-7094000030822,0003789-72.2020.8.22.0501,2020-07-01 22:14:52,2020-07-01 22:14:52,N
14810,15052,1730c24030bd053e,1730c24030bd053e,2020-07-01 20:49:12,2020-07-01 20:49:12,FWD: [2-2802000030799] QUEBRA DE SIGILO (00442...,lis-latam@google.com,"b'\r\n\r\nHi team,\r\n\r\nPlease see below the...","Hi team, Please see below the request LIS rece...",2,/home/dev/sigo_prod/_attachments/1730c24030bd053e,2-2802000030799,0004425-54.2019.8.16.0173,2020-07-01 22:03:16,2020-07-01 22:03:16,N
14183,14425,1730c16ed3c6cb77,1730c16ed3c6cb77,2020-07-01 20:34:53,2020-07-01 20:34:53,FWD: [6-2172000030245] BR Data Request 0000843...,lis-latam@google.com,b'\r\n\r\nUrgent 24hrs deadline / Fines.\r\n\r...,Urgent 24hrs deadline / Fines. Records # [0000...,2,/home/dev/sigo_prod/_attachments/1730c16ed3c6cb77,6-2172000030245,0000843-60.2020.8.01.0001,2020-07-01 21:44:40,2020-07-01 21:44:40,N
16415,16657,1730c0edb333c98c,1730c0edb333c98c,2020-07-01 20:26:06,2020-07-01 20:26:06,FWD: [4-7117000031013] BR Data Request 0816860...,lis-latam@google.com,b'\r\n\r\nRecords # [0816860-50.2019.4.05.8100...,Records # [0816860-50.2019.4.05.8100] Date rec...,2,/home/dev/sigo_prod/_attachments/1730c0edb333c98c,4-7117000031013,0816860-50.2019.4.05.8100,2020-07-01 22:49:32,2020-07-01 22:49:32,N
16297,16539,1730c0c30c56fc59,1730c0c30c56fc59,2020-07-01 20:23:11,2020-07-01 20:23:11,FWD: [3-7684000030774] BR Data Request IP 2239...,lis-latam@google.com,b'\r\n\r\nRecords #[IP 223957/2019]\r\n\r\nDat...,Records #[IP 223957/2019] Date received via LE...,2,/home/dev/sigo_prod/_attachments/1730c0c30c56fc59,3-7684000030774,,2020-07-01 22:46:04,2020-07-01 22:46:04,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2574,2575,16b6cb7c7e15c924,16b6cb7c7e15c924,2019-06-18 22:31:49,2019-06-18 22:31:49,Diligência - GAECO/Cascavel - PR,helena.rossi@carinaquito.com,"b'Dra. Alessandra,\r\n\r\n \r\n\r\nConforme fa...","Dra. Alessandra, Conforme falamos, enviaremos ...",1,/home/dev/sigo_prod/_attachments/16b6cb7c7e15c924,,,2020-07-01 13:34:06,2020-07-01 13:34:06,N
7462,7463,16b6cb6ff697c2af,16b6cb6ff697c2af,2019-06-18 22:30:58,2019-06-18 22:30:58,Diligência - Delegacia de Repressão a Corrupçã...,helena.rossi@carinaquito.com,"b'Dra. Carolina,\r\n\r\n \r\n\r\nConforme fala...","Dra. Carolina, Conforme falamos, enviaremos po...",1,/home/dev/sigo_prod/_attachments/16b6cb6ff697c2af,,,2020-07-01 15:57:23,2020-07-01 15:57:23,N
10127,10228,16b6cb501fd2e09b,16b6cb501fd2e09b,2019-06-18 22:28:47,2019-06-18 22:28:47,Diligência - Procuradoria da República no Rio ...,helena.rossi@carinaquito.com,"b'Dra. Carolina,\r\n\r\n \r\n\r\nConforme fala...","Dra. Carolina, Conforme falamos mais cedo, env...",1,/home/dev/sigo_prod/_attachments/16b6cb501fd2e09b,,,2020-07-01 18:47:18,2020-07-01 18:47:18,N
15566,15808,16b6cb4361be635d,16b6cb4361be635d,2019-06-18 22:27:56,2019-06-18 22:27:56,Diligência - Delegacia de Polícia de Goianésia...,helena.rossi@carinaquito.com,"b'Dra. Thalita,\r\n\r\n \r\n\r\nConforme falam...","Dra. Thalita, Conforme falamos, enviaremos por...",1,/home/dev/sigo_prod/_attachments/16b6cb4361be635d,,,2020-07-01 22:24:50,2020-07-01 22:24:50,N
5472,5473,16b66603ebd89f26,16b66603ebd89f26,2019-06-17 16:58:32,2019-06-17 16:58:32,Tips for using your new inbox,mail-noreply@google.com,b' Tips for using your new inbox\r\n[image: Go...,Hi Diligências Welcome to your Gmail inbox Sav...,1,/home/dev/sigo_prod/_attachments/16b66603ebd89f26,,,2020-07-01 14:57:03,2020-07-01 14:57:03,N

In [201]:
os.listdir(data_path)

['pid_DataCollector.dat',
 'to_data.csv',
 'att_data.csv',
 'log.csv',
 'subset_mail_error.dat',
 'mid_base.csv',
 'logging_app.log']

In [219]:
df_mid = pd.read_csv(os.path.join(data_path, 'mid_base.csv'), sep = '\t', encoding = 'utf-8')

In [220]:
df_mid

                     id          threadId       after      before
0      1709e2dba8f969ad  1708d1d9ae8b8645  2018-01-01  2020-03-04
1      1709e261f35d80fd  1709e261f35d80fd  2018-01-01  2020-03-04
2      1709e1b9dd48e838  1709e1b9dd48e838  2018-01-01  2020-03-04
3      1709e1669f34cff4  170692f5e2c5f209  2018-01-01  2020-03-04
4      1709df0f2361e2b3  1709df0f2361e2b3  2018-01-01  2020-03-04
...                 ...               ...         ...         ...
19724  17307c059fb51e77  17307c059fb51e77  2020-07-01  2020-07-02
19725  17307bea25e1d939  17307bea25e1d939  2020-07-01  2020-07-02
19726  17308e469942ded6  17306ea0a3aa2a34  2020-07-01  2020-07-02
19727  1730a322184c45b9  1730a322184c45b9  2020-07-01  2020-07-02
19728  1730a62c5baef99f  17300b01f44f8ad4  2020-07-01  2020-07-02

[19729 rows x 4 columns]

In [221]:
df_mid[df_mid['after'] == '2020-07-01']

                     id          threadId       after      before
19717  1730838f9d0a628b  1730365157aa6ad5  2020-07-01  2020-07-02
19718  173082f3ea9a8667  17281172f0ef8472  2020-07-01  2020-07-02
19719  1730828e53778db3  1730828e53778db3  2020-07-01  2020-07-02
19720  1730823982df7132  172f27e4f3f573f9  2020-07-01  2020-07-02
19721  173081f8682f389c  173081f8682f389c  2020-07-01  2020-07-02
19722  17307d345a6c0338  17307d345a6c0338  2020-07-01  2020-07-02
19723  17307c0a9e28e0bb  17307c0a9e28e0bb  2020-07-01  2020-07-02
19724  17307c059fb51e77  17307c059fb51e77  2020-07-01  2020-07-02
19725  17307bea25e1d939  17307bea25e1d939  2020-07-01  2020-07-02
19726  17308e469942ded6  17306ea0a3aa2a34  2020-07-01  2020-07-02
19727  1730a322184c45b9  1730a322184c45b9  2020-07-01  2020-07-02
19728  1730a62c5baef99f  17300b01f44f8ad4  2020-07-01  2020-07-02

In [229]:
## test DB ~ 20k mails (collect stopped 2020-07-01)
#cqdb.GetTable('screening_table')